name: shelf_ndjson_stream
description: A wrapper for easily streaming ndjson responses from a shelf server.
version: 0.1.0
homepage: https://github.com/alexobviously/shelf_ndjson_stream

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  shelf: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0